### ISSUE TITLE
Unable to executed the code in Readme.md even on playground

### ISSUE THREAD

**Issue by HiteshDutt** [mileusna/crontab#12]
Hi,

I was trying to use this library for my upcoming cron job, but the example itself hits exit(0). I have tried the example as is and even tried same in playground. Code is exiting.

Can you please help, If i need to do anything extra make cron job run?

here is link to play ground https://play.golang.org/p/p2jBT3dm9nw

**Comment by mileusna** [comment]
For this example to work you need to uncomment `time.Sleep()` part, otherwise program will just exit.

In real world application, your app will do something else, waiting for HTTP connections etc. while the cronjobs would be run in the background. But since this is just an example, you need `time.Sleep()` to stop the program and wait for cron jobs to execute.

Here it is the screenshot where you can see that it works (Hello world printed) with `time.Sleep()` uncommented

<img width="673" alt="Screenshot 2021-06-10 at 13 07 24" src="https://user-images.githubusercontent.com/4697935/121515208-39422380-c9ed-11eb-8114-04c7ac00c000.png">

**Comment by HiteshDutt** [comment]
Thank you for your response. I have not tried sleep, I actually was looking for always alive cron job , that would do action after every 30 mins.

I have used select{} after ctab.AddJob() and it works as expected

please let me know if there are any side effects of using select{}. 

As this is not an issue anymore I am closing this. 

Thanks you

**Comment by mileusna** [comment]
Cron job will be always active while your aplication is alive. It can not execute the code after your program is shutted down. 

Implementation depends on your programm, sleep is just for the demo.

**Comment by HiteshDutt** [comment]
Thank you for your time and crontab. really saves a lot of development effort.
