### ISSUE TITLE
Add ability to schedule already parsed expresstion

### ISSUE THREAD

**Issue by fred01** [mileusna/crontab#3]
It would be good to add one more function to directly add job struct, in case i have already parsed expression (i.e. i have int day, hour, week and so), or event better to schedule job at specific go time

**Comment by mileusna** [comment]
> to schedule job at specific go time

It might be good idea to add jobs that runs only once and then delete itself.

> to directly add job struct, in case i have already parsed expression

Well, job struct is un-exported, exporting it might confuse some users and make package more complicated and exposed to errors due to bad usage. I want to stick to crontab-like syntax (* * * * *) and parsing is really fast and done only once, so I don't see the reason to provide struct directly.

I guess you have some use case which is different than the way I usually use the package.

**Comment by fred01** [comment]
Ok, got it. Yes, i would use it as general-purpose scheduler, for example call function at specified time in future, in that case add Job at time would be more convenient way to do this, instead of combining cron expression. In any way, thank you for answer, i closing it for now.
